
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import Header from "@/components/navigation-header";
import Footer from "@/components/footer";
import Providers from "@/Providers/Providers";
import { Toaster } from "sonner";
import Message from "@/components/message";
import ProtectedLayout from "@/hook/ProtectedLayout";
import { LanguageProvider } from "@/components/LanguageProvider";
import InitialLoadGate from "@/components/initial-load-gate";

// Load Poppins with `variable` option
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Crypto-Education-Platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* Google Tag Manager */}
        <Script
          id="google-tag-manager"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-K4M22CCN');`,
          }}
        />
      </head>
      <body
        className={`${poppins.variable} antialiased`}
        style={{ fontFamily: "var(--font-poppins)" }}
        cz-shortcut-listen="true"
      >
        {/* Google Tag Manager (noscript) */}
        <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-K4M22CCN"
            height="0"
            width="0"
            style={{ display: "none", visibility: "hidden" }}
          />
        </noscript>
        <LanguageProvider>
            <Providers>
              <InitialLoadGate>
                <Toaster />
                <Header />
                <ProtectedLayout>
                  {children}
                </ProtectedLayout>
                <Message />
                <Footer />
              </InitialLoadGate>
            </Providers>
          </LanguageProvider>
        
      </body>
    </html>
  );
}
