
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/navigation-header";
import Footer from "@/components/footer";
import Providers from "@/Providers/Providers";
import { Toaster } from "sonner";
import Message from "@/components/message";
import ProtectedLayout from "@/hook/ProtectedLayout";
import { LanguageProvider } from "@/components/LanguageProvider";

// Load Poppins with `variable` option
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Crypto-Education-Frontend",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased`}
        style={{ fontFamily: "var(--font-poppins)" }}
        cz-shortcut-listen="true"
      >
        <LanguageProvider>
          <Providers>
            <Toaster />
            <Header />
            <ProtectedLayout>
            {children}
            </ProtectedLayout>
            <Message />
            <Footer />
          </Providers>
        </LanguageProvider>
      </body>
    </html>
  );
}
