name: 🚀 Deploy Crypto to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_PASS_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /root/crypto-eduction-frontend
            git pull origin main
            npm install
            npm run build
            pm2 reload ${{ secrets.APP_NAME }} || pm2 start npm --name ${{ secrets.APP_NAME }} -- start
